name: New Test Case
description: Suggest or request a new feature
labels: ["test case"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly define the test case.
  - type: textarea
    id: description
    attributes:
      label: Test Case ID
      placeholder: Provide Test Case ID
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Objective
      placeholder: To verify login functionality
  - type: textarea
    id: context
    attributes:
      label: Steps
      placeholder: |
        Provide steps to execute the test case.
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Let's see together if it can be implemented.
